Repository AIGOO-Epson/frontend, pull requests merged in 2024-06, with the labels that each got.

#5 feat: navbar 컴포넌트 생성 및 라우팅 기능 작업
  src/app/layout.tsx
  src/components/NavBar.tsx
  src/components/NavMenu.tsx
  src/lib/constants/navMenuItems.ts
Labels: Feature

#9 Chore: tanskquery v5 및 shandcn-ui 설치
  components.json
  package-lock.json
  package.json
  src/app/global.css
  src/app/layout.tsx
  src/components/ui/tabs.tsx
  src/hooks/mutations/.gitkeep
  src/hooks/queries/.gitkeep
  src/lib/util/ReactQueryProvider.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: Chore

#10 refactor: 디렉토리 변경 및 라우팅 방식 변경
  src/app/globals.css
  src/app/layout.tsx
  src/components/NavMenu.tsx
  src/components/common/navbar/NavBar.tsx
  src/components/common/navbar/NavMenu.tsx
Labels: Refactor

#15 feat: nav bar 스타일 변경
  src/components/common/navbar/NavBar.tsx
Labels: Feature

#16 feat: 메인 페이지 전반적인 레이아웃 작업 진행
  public/iu_demo.jpeg
  public/편지쓰기.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/main/ArticleSection.tsx
  src/components/main/DateSection.tsx
  src/components/main/DynamicLetterComponet.tsx
  src/components/main/RecentLetterSection.tsx
  src/components/main/WeeklyCalendar.tsx
  src/lib/constants/mocking.ts
  src/lib/util/ReactQueryProvider.tsx
Labels: Feature

#21 로그인, 로그아웃 관련 작
  package-lock.json
  package.json
  public/arrow_back_ios.png
  public/default_profile.svg
  public/notifications.png
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/button/BackButton.tsx
  src/components/header/BackHeader.tsx
  src/components/header/Header.tsx
  src/components/header/MainHeader.tsx
  src/components/header/RenderHeader.tsx
  src/components/header/SendHeader.tsx
  src/components/header/signin/Signin.tsx
  src/components/header/userInfo/UserInfo.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/lib/api/api.ts
  src/lib/api/axiosClient.ts
  src/lib/constants/mocking.ts
  src/lib/util/cookies.ts
  src/store/useAuthStore.tsx
  src/store/useUserStore.tsx
Labels: Feature

#24 네비게이션 바 스타일 변경
  src/components/common/navbar/NavBar.tsx
Labels: Refactor

#22 메인 페이지 일부 스타일 변경 및 로그인 상태에 따른 예외처리 작업
  src/app/layout.tsx
  src/app/page.tsx
  src/components/main/ArticleSection.tsx
  src/components/main/DateSection.tsx
  src/components/main/RecentLetterSection.tsx
Labels: Feature

#25 Feat: 우편함 페이지 구현
  src/app/mailbox/page.tsx
  src/app/material/page.tsx
  src/components/mailbox/Mail.tsx
  src/components/mailbox/MailList.tsx
  src/components/mailbox/Mailbox.tsx
  src/components/ui/tabs.tsx
  src/hooks/queries/useMailListQuery.ts
  src/lib/api/api.ts
  src/lib/api/axiosClient.ts
  src/lib/constants/navMenuItems.ts
Labels: Feature

#28 페이지 별 헤더 구분 및 로그인, 로그아웃 상태 관리
  public/arrow_back.png
  public/arrow_back_ios.png
  public/custom_typography.png
  public/print.png
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/button/BackButton.tsx
  src/components/header/MainHeader.tsx
  src/components/header/PrintHeader.tsx
  src/components/header/RenderHeader.tsx
  src/components/header/SendHeader.tsx
  src/components/header/SimpleHeader.tsx
  src/components/header/UserHeader.tsx
  src/components/header/signin/Signin.tsx
  src/components/header/simple/OriginImageHeader.tsx
  src/components/header/simple/PrinterHeader.tsx
  src/components/header/simple/ScanHeader.tsx
  src/components/header/simple/SendHeader.tsx
  src/components/header/userInfo/UserInfo.tsx
  src/components/header/userInfoHeader/MailBox.tsx
  src/components/header/userInfoHeader/MainSelectArtist.tsx
  src/components/header/userInfoHeader/MaterialHeader.tsx
  src/lib/constants/pathname.ts
  src/lib/util/AuthGuard.tsx
  src/lib/util/cookies.ts
  src/store/useAuthStore.tsx
  src/store/useUserStore.tsx
Labels: Feature

#30 Feat: 학습자료 페이지 구현
  public/printer.svg
  src/app/material/[id]/page.tsx
  src/app/material/page.tsx
  src/components/mailbox/Mailbox.tsx
  src/components/material/Material.tsx
  src/components/material/MaterialPDF.tsx
  src/components/material/Materials.tsx
  src/hooks/queries/useMailListQuery.ts
  src/hooks/queries/useMaterialQuery.ts
  src/lib/api/api.ts
Labels: Feature

#29 userData 타입 처리에 따른 옵셔널 추가
  src/app/page.tsx
Labels: Feature, Refactor

#33 일부 페이지 네비게이션 보이지 않게 수정 및 편지 보내기 플로우 수정
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/navbar/NavBar.tsx
  src/components/header/signin/Signin.tsx
  src/components/header/userInfo/UserInfo.tsx
  src/components/main/SendMailSelect.tsx
Labels: Feature

#34 헤더 렌더링 되는 부분 수정 및 경로 상수화 등
  src/components/header/PrintHeader.tsx
  src/components/header/RenderHeader.tsx
  src/components/header/SimpleHeader.tsx
  src/components/header/simple/SendHeader.tsx
  src/lib/constants/pathname.ts
  src/lib/util/CheckPathName.tsx
Labels: Feature

#35 스캔으로 편지 보내기 유효성 검사 및 플로우 적용 및 관련 작업
  package-lock.json
  package.json
  src/app/globals.css
  src/app/mailscan/page.tsx
  src/components/common/spacing/Spacing.tsx
  src/components/sendMail/List.tsx
  src/components/sendMail/ScanPage.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/sonner.tsx
  src/lib/api/api.ts
Labels: Feature

#38 Feat: 학습자료 페이지, 우편함 페이지 기능 추가
  package-lock.json
  package.json
  src/app/material/[id]/page.tsx
  src/components/header/PrintHeader.tsx
  src/components/mailbox/Mail.tsx
  src/components/mailbox/MailList.tsx
  src/components/material/Material.tsx
  src/components/material/MaterialPDF.tsx
  src/components/material/Materials.tsx
  src/hooks/queries/useMaterialQuery.ts
  src/lib/api/api.ts
  src/store/usePrintStore.tsx
Labels: Feature

#37 style: 네이게이션 바 스타일 변경 및 아티스트 선택 부분 스타일 변경
  src/components/common/navbar/NavBar.tsx
  src/components/header/userInfoHeader/MainSelectArtist.tsx
Labels: Feature

#39 편지 보내기(스캔) 페이지 작업
  public/icon-scan.gif
  src/app/mailbox/[letterDocumentId]/keywords/page.tsx
  src/app/mailscan/page.tsx
  src/app/mailscan/scan/page.tsx
  src/components/scan/ScanPage.tsx
  src/components/sendMail/SendMailScanPage.tsx
  src/hooks/useDeviceConnect.tsx
  src/lib/api/api.ts
Labels: Feature

#40 헤더 렌더링 관련 경로 추가 및 일부 스타일 변경
  src/app/globals.css
  src/components/header/RenderHeader.tsx
  src/components/header/UserHeader.tsx
  src/components/header/userInfo/UserInfo.tsx
  src/components/ui/button.tsx
  src/lib/util/CheckPathName.tsx
  src/store/useUserStore.ts
Labels: Feature

#42 fix: 코드 오류 수정
  src/lib/api/api.ts
Labels: Fix

#46 편지 보내기 스캔, 업로드 방식 페이지 구현 및 로딩 페이지 구현
  public/add.png
  public/rocket.gif
  src/app/globals.css
  src/app/mailscan/scan/page.tsx
  src/app/mailupload/page.tsx
  src/components/header/RenderHeader.tsx
  src/components/scan/ScanPage.tsx
  src/components/sendFlow/ScanGuideLine.tsx
  src/components/sendFlow/ScanPage.tsx
  src/components/sendFlow/SendLoading.tsx
  src/components/sendMail/ScanPage.tsx
  src/components/sendMail/SendMailScanPage.tsx
  src/components/sendMail/SendMailUpload.tsx
  src/hooks/useDeviceConnect.tsx
  src/lib/api/api.ts
  src/store/useScanStore.ts
  src/store/useSentStore.ts
  src/store/useTitleStore.ts
Labels: Feature

#48 feat: 인쇄 Toast UI 추가
  src/components/header/PrintHeader.tsx
Labels: Feature

#56 Feat: ScrollTop 구현 및 스타일 수정
  public/search_check_2.svg
  public/vertical_align_top.svg
  src/components/common/button/ScrollTop.tsx
  src/components/mailbox/Mail.tsx
  src/components/mailbox/MailList.tsx
  src/components/mailbox/Mailbox.tsx
  src/components/material/Material.tsx
  src/components/material/Materials.tsx
Labels: Feature

#53 네비게이션 바 메뉴탭 클릭 상태 추가 및 스타일 변경
  src/components/common/navbar/NavBar.tsx
  src/components/common/navbar/NavMenu.tsx
  src/lib/constants/navMenuItems.ts
  src/store/useIsCheckedStore.ts
Labels: Feature, Refactor

#54 편지 보내기 부분 로딩 페이지 이미지 변경 및 전체적인 스타일 변경
  src/components/sendFlow/ScanPage.tsx
  src/components/sendFlow/SendLoading.tsx
  src/components/sendMail/List.tsx
  src/components/sendMail/SendMailScanPage.tsx
  src/components/sendMail/SendMailUpload.tsx
  src/lib/constants/pathname.ts
Labels: Refactor

#55 메인 페이지 전체적인 스타일 변경 작업 및 최근 받은 편지 섹션 작업
  next.config.mjs
  public/description.png
  public/description_fill.png
  public/edit.svg
  public/home.png
  public/home_fill.png
  public/mail.png
  public/mail_fill.png
  public/photo_alternate.png
  public/scanner.png
  public/send_loading.gif
  src/app/globals.css
  src/app/page.tsx
  src/components/main/ArticleSection.tsx
  src/components/main/DateSection.tsx
  src/components/main/DynamicLetterComponet.tsx
  src/components/main/LetterImage.tsx
  src/components/main/RecentLetterSection.tsx
  src/components/main/SendMailSelect.tsx
  src/components/main/WeeklyCalendar.tsx
  src/components/ui/button.tsx
  src/components/ui/dropdown-menu.tsx
  src/hooks/queries/useGetMailDetail.ts
  src/hooks/useOutsideClick.tsx
  src/lib/api/api.ts
  src/store/useIsOpenStore.ts
  tailwind.config.ts
Labels: Feature, Refactor

#59 영문으로 변경 작업 진행 및 스타일 변경 작업
  public/guide_line.png
  public/icon-scan.gif
  public/log_out.png
  public/next.svg
  public/notifications.png
  public/notifications.svg
  src/app/globals.css
  src/app/page.tsx
  src/components/common/button/ScrollTop.tsx
  src/components/common/navbar/NavBar.tsx
  src/components/header/Header.tsx
  src/components/header/UserHeader.tsx
  src/components/header/signin/Signin.tsx
  src/components/header/simple/OriginImageHeader.tsx
  src/components/header/simple/ScanHeader.tsx
  src/components/header/simple/SendHeader.tsx
  src/components/header/userInfo/UserInfo.tsx
  src/components/header/userInfoHeader/MailBox.tsx
  src/components/header/userInfoHeader/MainSelectArtist.tsx
  src/components/header/userInfoHeader/MaterialHeader.tsx
  src/components/mailbox/Mailbox.tsx
  src/components/main/ArticleSection.tsx
  src/components/main/DateSection.tsx
  src/components/main/DynamicLetterComponet.tsx
  src/components/main/RecentLetterSection.tsx
  src/components/main/SendMailSelect.tsx
  src/components/main/WeeklyCalendar.tsx
  src/components/sendFlow/ScanGuideLine.tsx
  src/components/sendMail/SendMailScanPage.tsx
  src/components/sendMail/SendMailUpload.tsx
  src/components/ui/dropdown-menu.tsx
  src/hooks/useDeviceConnect.tsx
  src/lib/constants/mocking.ts
  src/lib/constants/navMenuItems.ts
Labels: Refactor

#69 로그인 및 로그아웃 상태관리 및 관련 로직 최적화
  public/cover.jpg
  src/components/header/userInfo/UserInfo.tsx
  src/components/main/DynamicLetterComponet.tsx
  src/components/main/LetterImage.tsx
  src/components/sendFlow/SendLoading.tsx
  src/hooks/queries/useMailListQuery.ts
  src/lib/api/api.ts
  src/lib/util/AuthGuard.tsx
  src/store/useRecentLettersStore.ts
Labels: Refactor

#83 refactor: Mail status 값 수정
  src/components/mailbox/Mail.tsx
Labels: Refactor

#84 로그인 관련 상태 체크 로직 변경 및 protected routing 적용, redirect 페이지 구현 및 404 커스텀 페이지 추가
  public/login.gif
  src/app/mailscan/page.tsx
  src/app/mailupload/page.tsx
  src/app/not-found.tsx
  src/app/notes/[id]/page.tsx
  src/app/notes/page.tsx
  src/app/page.tsx
  src/components/RedirectPage.tsx
  src/components/common/navbar/NavBar.tsx
  src/components/header/Header.tsx
  src/components/header/UserHeader.tsx
  src/components/header/signin/Signin.tsx
  src/components/header/userInfo/UserInfo.tsx
  src/components/mailDetail/keywordSelect/SelectKeywords.tsx
  src/components/mailDetail/mailInfo/MailDetail.tsx
  src/components/mailDetail/mailPrint/PrintMail.tsx
  src/components/mailbox/Mailbox.tsx
  src/components/material/Material.tsx
  src/components/material/Materials.tsx
  src/components/sendFlow/ScanPage.tsx
  src/components/sendMail/SendMailScanPage.tsx
  src/components/sendMail/SendMailUpload.tsx
  src/lib/constants/navMenuItems.ts
  src/lib/constants/pathname.ts
  src/lib/util/AuthGuard.tsx
  src/lib/util/WithAuth.tsx
  src/store/useIsCheckedLoadingStroe.ts
Labels: Feature, Refactor
